In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns


%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [51]:
n = np.arange(1, 21)
ans = 2 ** n / n
ans

array([  2.00000000e+00,   2.00000000e+00,   2.66666667e+00,
         4.00000000e+00,   6.40000000e+00,   1.06666667e+01,
         1.82857143e+01,   3.20000000e+01,   5.68888889e+01,
         1.02400000e+02,   1.86181818e+02,   3.41333333e+02,
         6.30153846e+02,   1.17028571e+03,   2.18453333e+03,
         4.09600000e+03,   7.71011765e+03,   1.45635556e+04,
         2.75941053e+04,   5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [49]:
i = np.arange(0, 6)
s = 0.1 ** (3 * i) * 0.2 ** (4 * i)
ans = s.sum()
ans

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [48]:
A = np.zeros((8, 8))
A[::2, ::2] = 1
A[1::2, 1::2] = 1
A

array([[ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [47]:
X = np.random.random((5, 2))
r = np.sqrt(X[:, 0] ** 2 + X[:, 1] ** 2)
X[:, 1] = np.arccos(X[:, 0] / r)
X[:, 0] = r
X

array([[ 1.14139087,  0.51137492],
       [ 0.98648433,  0.29292124],
       [ 1.09414519,  0.80766527],
       [ 0.81248109,  0.54846396],
       [ 0.39259267,  0.63085991]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [7]:
#контрпример
X = np.ones((3,3))
X[1:,2]=3
X[:2,0]=6
X[0,2]=8
X[2,0]=8
print(X)

i = np.argmax(np.max(X, axis=1))
j = np.argmax(np.max(X, axis=0))
if X[i,j] != np.max(X):
    print(np.max(X, axis=1),np.max(X, axis=0))
    print(i,j,X[i,j],  np.max(X))
    raise "no max"
else:
    print(i,j,X[i,j])

[[ 6.  1.  8.]
 [ 6.  1.  3.]
 [ 8.  1.  3.]]
[ 8.  6.  8.] [ 8.  1.  8.]
0 0 6.0 8.0


TypeError: exceptions must derive from BaseException

In [34]:
X = np.random.random((10, 10))
i = np.argmax(np.max(X, axis=1))
j = np.argmax(np.max(X, axis=0))
if X[i,j] != np.max(X):
    print(np.max(X, axis=1),np.max(X, axis=0))
    print(i,j,X[i,j],  np.max(X))
    raise "no max"
else:
    print(i,j,X[i,j])
print(X)

4 3 0.962228290068
[[ 0.68018     0.09416977  0.19876119  0.49060303  0.95990034  0.20868285
   0.71455928  0.32247603  0.75838839  0.61937029]
 [ 0.52272074  0.23329512  0.47811393  0.01789529  0.35675563  0.01995606
   0.9444755   0.04416745  0.38889288  0.77407822]
 [ 0.60767166  0.77647785  0.64809419  0.10461937  0.34041416  0.84809427
   0.2916371   0.35635942  0.34417277  0.07594458]
 [ 0.12950091  0.11153253  0.34119082  0.69341853  0.77283437  0.412039
   0.83664269  0.23496066  0.09635593  0.22465411]
 [ 0.10308235  0.37841329  0.93276578  0.96222829  0.88000348  0.4038135
   0.30979214  0.89129762  0.02964352  0.91723675]
 [ 0.51304892  0.04719748  0.94955276  0.01718604  0.4746372   0.7984439
   0.01363014  0.21835494  0.26337858  0.34720048]
 [ 0.91833584  0.77593375  0.33056076  0.2288611   0.35488483  0.57737025
   0.33043432  0.19067447  0.18025476  0.17514051]
 [ 0.12514338  0.41465023  0.15752136  0.75253637  0.60060879  0.78982736
   0.75249661  0.85015555  0.5066341

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [46]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
ans = X[np.argmin(np.sqrt(((X[:,0] - y[0,0]) ** 2 + (X[:,1] - y[0,1]) ** 2))), :]
ans

array([ 0.93223758,  0.7214819 ])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [45]:
@np.vectorize
def f(x):
    if x < 0: return x ** 2 + 2 * x + 6
    elif x < 2: return x + 6
    else: return x ** 2 + 4 * x - 4
    
x = np.arange(-3, 3.00001, 0.5)
ans = f(x)
ans

array([  9.  ,   7.25,   6.  ,   5.25,   5.  ,   5.25,   6.  ,   6.5 ,
         7.  ,   7.5 ,   8.  ,  12.25,  17.  ])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [43]:
X = np.random.random((10, 10))
med = np.mean(X, axis=1)
X = (X.T - med).T
np.mean(X, axis=1)

array([  2.22044605e-17,  -3.33066907e-17,  -6.66133815e-17,
        -8.88178420e-17,   2.22044605e-17,  -6.66133815e-17,
        -3.33066907e-17,   4.44089210e-17,  -2.22044605e-17,
        -4.44089210e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [38]:
X = np.random.normal(loc=5, scale=2., size=1000)
MX = np.mean(X)
DX = np.std(X) ** 2
print(MX)
print(DX)

4.88189847122
3.85912147929


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [36]:
A = np.zeros((5,5))
A[0:5, :] = np.arange(5)
A[1,:] = np.roll(A[0,:], -1)
A[2,:] = np.roll(A[1,:], -1)
A[3,:] = np.roll(A[2,:], -1)
A[4,:] = np.roll(A[3,:], -1)
A

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.,  0.],
       [ 2.,  3.,  4.,  0.,  1.],
       [ 3.,  4.,  0.,  1.,  2.],
       [ 4.,  0.,  1.,  2.,  3.]])

In [35]:
z = np.random.normal(size=5)
print(z)
print(np.sum(z))
print(z[0]+z[1]+z[2])

[-0.2848452  -1.01823845 -0.14292637 -0.35320805  0.09978189]
-1.69943618783
-1.4460100284
